# AP/AR Orchestrator Data Inspection
This notebook allows you to inspect the synthetic datasets generated for the orchestration engine.

In [1]:
import pandas as pd
import json

# Load the CSV files
po_df = pd.read_csv('../data/purchase_orders.csv')
gr_df = pd.read_csv('../data/goods_receipts.csv')
ar_df = pd.read_csv('../data/customer_invoices.csv')

In [2]:
print(f"Total Purchase Orders: {len(po_df)}")
display(po_df.head())
po_df.info()

Total Purchase Orders: 100

,po_number,vendor_id,expected_total,line_items
0,PO-1001,VEND-128,3780.0,"[{""item_id"": ""ITEM-109"", ""description"": ""Solid..."
1,PO-1002,VEND-111,11600.0,"[{""item_id"": ""ITEM-110"", ""description"": ""Stand..."
2,PO-1003,VEND-111,750.0,"[{""item_id"": ""ITEM-101"", ""description"": ""Stand..."
3,PO-1004,VEND-115,1440.0,"[{""item_id"": ""ITEM-106"", ""description"": ""Cat6 ..."
4,PO-1005,VEND-109,9750.0,"[{""item_id"": ""ITEM-105"", ""description"": ""27-In..."

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   po_number       100 non-null    str
 1   vendor_id       100 non-null    str
 2   expected_total  100 non-null    float64
 3   line_items      100 non-null    str
dtypes: float64(1), str(3)
memory usage: 3.3 KB

In [3]:
print(f"Total Goods Receipts: {len(gr_df)}")
display(gr_df.head())
gr_df.info()

Total Goods Receipts: 92

,receipt_id,po_number,received_quantity,line_items
0,GR-9001,PO-1001,21.0,"[{""item_id"": ""ITEM-109"", ""description"": ""Solid..."
1,GR-9002,PO-1002,29.0,"[{""item_id"": ""ITEM-110"", ""description"": ""Stand..."
2,GR-9003,PO-1003,5.0,"[{""item_id"": ""ITEM-101"", ""description"": ""Stand..."
3,GR-9004,PO-1004,12.0,"[{""item_id"": ""ITEM-106"", ""description"": ""Cat6 ..."
4,GR-9005,PO-1005,39.0,"[{""item_id"": ""ITEM-105"", ""description"": ""27-In..."

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   receipt_id         92 non-null     str
 1   po_number          92 non-null     str
 2   received_quantity  92 non-null     float64
 3   line_items         92 non-null     str
dtypes: float64(1), str(3)
memory usage: 3.0 KB

In [4]:
print(f"Total Customer Invoices: {len(ar_df)}")
display(ar_df.head())
ar_df.info()

Total Customer Invoices: 100

,invoice_number,customer_id,total_amount,amount_paid,due_date,status
0,INV-2001,CUST-238,5926.97,2370.79,2026-10-08,PROCESSING
1,INV-2002,CUST-250,13525.50,0.00,2026-10-14,UNPAID
2,INV-2003,CUST-202,1617.96,0.00,2026-10-21,UNPAID
3,INV-2004,CUST-237,8344.11,3337.64,2026-10-19,PROCESSING
4,INV-2005,CUST-208,3105.52,1242.21,2026-10-21,PROCESSING

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  100 non-null    str
 1   customer_id     100 non-null    str
 2   total_amount    100 non-null    float64
 3   amount_paid     100 non-null    float64
 4   due_date        100 non-null    str
 5   status          100 non-null    str
dtypes: float64(2), str(4)
memory usage: 4.8 KB

In [5]:
# Example: Parsing the JSON in line_items to see the exact item schema
print("Sample Line Items from PO-1001:")
sample_items = json.loads(po_df.loc[0, 'line_items'])
print(json.dumps(sample_items, indent=2))

Sample Line Items from PO-1001:
[
  {
    "item_id": "ITEM-109",
    "description": "Solid State Drive 2TB NVMe",
    "quantity": 21.0,
    "unit_price": 180.0,
    "total_price": 3780.0
  }
]